/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SaudeRouteImport } from './routes/saude'
import { Route as RecompensasRouteImport } from './routes/recompensas'
import { Route as PersonalizarAvatarRouteImport } from './routes/personalizar-avatar'
import { Route as MaisRouteImport } from './routes/mais'
import { Route as JogosRouteImport } from './routes/jogos'
import { Route as AvatarRouteImport } from './routes/avatar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SaudeIndexRouteImport } from './routes/saude.index'
import { Route as SaudePressaoRouteImport } from './routes/saude.pressao'
import { Route as SaudeMedicamentosRouteImport } from './routes/saude.medicamentos'
import { Route as SaudeHumorRouteImport } from './routes/saude.humor'
import { Route as SaudeGlicemiaRouteImport } from './routes/saude.glicemia'
import { Route as SaudeFemininaRouteImport } from './routes/saude.feminina'
import { Route as SaudeAtividadeRouteImport } from './routes/saude.atividade'
import { Route as SaudeAlimentacaoRouteImport } from './routes/saude.alimentacao'
import { Route as SaudeAguaRouteImport } from './routes/saude.agua'

const SaudeRoute = SaudeRouteImport.update({
    id: '/saude',
    path: '/saude',
    getParentRoute: () => rootRouteImport,
} as any)
const RecompensasRoute = RecompensasRouteImport.update({
    id: '/recompensas',
    path: '/recompensas',
    getParentRoute: () => rootRouteImport,
} as any)
const PersonalizarAvatarRoute = PersonalizarAvatarRouteImport.update({
    id: '/personalizar-avatar',
    path: '/personalizar-avatar',
    getParentRoute: () => rootRouteImport,
} as any)
const MaisRoute = MaisRouteImport.update({
    id: '/mais',
    path: '/mais',
    getParentRoute: () => rootRouteImport,
} as any)
const JogosRoute = JogosRouteImport.update({
    id: '/jogos',
    path: '/jogos',
    getParentRoute: () => rootRouteImport,
} as any)
const AvatarRoute = AvatarRouteImport.update({
    id: '/avatar',
    path: '/avatar',
    getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
} as any)
const SaudeIndexRoute = SaudeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SaudeRoute,
} as any)
const SaudePressaoRoute = SaudePressaoRouteImport.update({
    id: '/pressao',
    path: '/pressao',
    getParentRoute: () => SaudeRoute,
} as any)
const SaudeMedicamentosRoute = SaudeMedicamentosRouteImport.update({
    id: '/medicamentos',
    path: '/medicamentos',
    getParentRoute: () => SaudeRoute,
} as any)
const SaudeHumorRoute = SaudeHumorRouteImport.update({
    id: '/humor',
    path: '/humor',
    getParentRoute: () => SaudeRoute,
} as any)
const SaudeGlicemiaRoute = SaudeGlicemiaRouteImport.update({
    id: '/glicemia',
    path: '/glicemia',
    getParentRoute: () => SaudeRoute,
} as any)
const SaudeFemininaRoute = SaudeFemininaRouteImport.update({
    id: '/feminina',
    path: '/feminina',
    getParentRoute: () => SaudeRoute,
} as any)
const SaudeAtividadeRoute = SaudeAtividadeRouteImport.update({
    id: '/atividade',
    path: '/atividade',
    getParentRoute: () => SaudeRoute,
} as any)
const SaudeAlimentacaoRoute = SaudeAlimentacaoRouteImport.update({
    id: '/alimentacao',
    path: '/alimentacao',
    getParentRoute: () => SaudeRoute,
} as any)
const SaudeAguaRoute = SaudeAguaRouteImport.update({
    id: '/agua',
    path: '/agua',
    getParentRoute: () => SaudeRoute,
} as any)

export interface FileRoutesByFullPath {
    '/': typeof IndexRoute
    '/avatar': typeof AvatarRoute
    '/jogos': typeof JogosRoute
    '/mais': typeof MaisRoute
    '/personalizar-avatar': typeof PersonalizarAvatarRoute
    '/recompensas': typeof RecompensasRoute
    '/saude': typeof SaudeRouteWithChildren
    '/saude/agua': typeof SaudeAguaRoute
    '/saude/alimentacao': typeof SaudeAlimentacaoRoute
    '/saude/atividade': typeof SaudeAtividadeRoute
    '/saude/feminina': typeof SaudeFemininaRoute
    '/saude/glicemia': typeof SaudeGlicemiaRoute
    '/saude/humor': typeof SaudeHumorRoute
    '/saude/medicamentos': typeof SaudeMedicamentosRoute
    '/saude/pressao': typeof SaudePressaoRoute
    '/saude/': typeof SaudeIndexRoute
}
export interface FileRoutesByTo {
    '/': typeof IndexRoute
    '/avatar': typeof AvatarRoute
    '/jogos': typeof JogosRoute
    '/mais': typeof MaisRoute
    '/personalizar-avatar': typeof PersonalizarAvatarRoute
    '/recompensas': typeof RecompensasRoute
    '/saude/agua': typeof SaudeAguaRoute
    '/saude/alimentacao': typeof SaudeAlimentacaoRoute
    '/saude/atividade': typeof SaudeAtividadeRoute
    '/saude/feminina': typeof SaudeFemininaRoute
    '/saude/glicemia': typeof SaudeGlicemiaRoute
    '/saude/humor': typeof SaudeHumorRoute
    '/saude/medicamentos': typeof SaudeMedicamentosRoute
    '/saude/pressao': typeof SaudePressaoRoute
    '/saude': typeof SaudeIndexRoute
}
export interface FileRoutesById {
    __root__: typeof rootRouteImport
    '/': typeof IndexRoute
    '/avatar': typeof AvatarRoute
    '/jogos': typeof JogosRoute
    '/mais': typeof MaisRoute
    '/personalizar-avatar': typeof PersonalizarAvatarRoute
    '/recompensas': typeof RecompensasRoute
    '/saude': typeof SaudeRouteWithChildren
    '/saude/agua': typeof SaudeAguaRoute
    '/saude/alimentacao': typeof SaudeAlimentacaoRoute
    '/saude/atividade': typeof SaudeAtividadeRoute
    '/saude/feminina': typeof SaudeFemininaRoute
    '/saude/glicemia': typeof SaudeGlicemiaRoute
    '/saude/humor': typeof SaudeHumorRoute
    '/saude/medicamentos': typeof SaudeMedicamentosRoute
    '/saude/pressao': typeof SaudePressaoRoute
    '/saude/': typeof SaudeIndexRoute
}
export interface FileRouteTypes {
    fileRoutesByFullPath: FileRoutesByFullPath
    fullPaths:
    | '/'
    | '/avatar'
    | '/jogos'
    | '/mais'
    | '/personalizar-avatar'
    | '/recompensas'
    | '/saude'
    | '/saude/agua'
    | '/saude/alimentacao'
    | '/saude/atividade'
    | '/saude/feminina'
    | '/saude/glicemia'
    | '/saude/humor'
    | '/saude/medicamentos'
    | '/saude/pressao'
    | '/saude/'
    fileRoutesByTo: FileRoutesByTo
    to:
    | '/'
    | '/avatar'
    | '/jogos'
    | '/mais'
    | '/personalizar-avatar'
    | '/recompensas'
    | '/saude/agua'
    | '/saude/alimentacao'
    | '/saude/atividade'
    | '/saude/feminina'
    | '/saude/glicemia'
    | '/saude/humor'
    | '/saude/medicamentos'
    | '/saude/pressao'
    | '/saude'
    id:
    | '__root__'
    | '/'
    | '/avatar'
    | '/jogos'
    | '/mais'
    | '/personalizar-avatar'
    | '/recompensas'
    | '/saude'
    | '/saude/agua'
    | '/saude/alimentacao'
    | '/saude/atividade'
    | '/saude/feminina'
    | '/saude/glicemia'
    | '/saude/humor'
    | '/saude/medicamentos'
    | '/saude/pressao'
    | '/saude/'
    fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
    IndexRoute: typeof IndexRoute
    AvatarRoute: typeof AvatarRoute
    JogosRoute: typeof JogosRoute
    MaisRoute: typeof MaisRoute
    PersonalizarAvatarRoute: typeof PersonalizarAvatarRoute
    RecompensasRoute: typeof RecompensasRoute
    SaudeRoute: typeof SaudeRouteWithChildren
}

declare module '@tanstack/react-router' {
    interface FileRoutesByPath {
        '/saude': {
            id: '/saude'
            path: '/saude'
            fullPath: '/saude'
            preLoaderRoute: typeof SaudeRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/recompensas': {
            id: '/recompensas'
            path: '/recompensas'
            fullPath: '/recompensas'
            preLoaderRoute: typeof RecompensasRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/personalizar-avatar': {
            id: '/personalizar-avatar'
            path: '/personalizar-avatar'
            fullPath: '/personalizar-avatar'
            preLoaderRoute: typeof PersonalizarAvatarRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/mais': {
            id: '/mais'
            path: '/mais'
            fullPath: '/mais'
            preLoaderRoute: typeof MaisRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/jogos': {
            id: '/jogos'
            path: '/jogos'
            fullPath: '/jogos'
            preLoaderRoute: typeof JogosRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/avatar': {
            id: '/avatar'
            path: '/avatar'
            fullPath: '/avatar'
            preLoaderRoute: typeof AvatarRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/': {
            id: '/'
            path: '/'
            fullPath: '/'
            preLoaderRoute: typeof IndexRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/saude/': {
            id: '/saude/'
            path: '/'
            fullPath: '/saude/'
            preLoaderRoute: typeof SaudeIndexRouteImport
            parentRoute: typeof SaudeRoute
        }
        '/saude/pressao': {
            id: '/saude/pressao'
            path: '/pressao'
            fullPath: '/saude/pressao'
            preLoaderRoute: typeof SaudePressaoRouteImport
            parentRoute: typeof SaudeRoute
        }
        '/saude/medicamentos': {
            id: '/saude/medicamentos'
            path: '/medicamentos'
            fullPath: '/saude/medicamentos'
            preLoaderRoute: typeof SaudeMedicamentosRouteImport
            parentRoute: typeof SaudeRoute
        }
        '/saude/humor': {
            id: '/saude/humor'
            path: '/humor'
            fullPath: '/saude/humor'
            preLoaderRoute: typeof SaudeHumorRouteImport
            parentRoute: typeof SaudeRoute
        }
        '/saude/glicemia': {
            id: '/saude/glicemia'
            path: '/glicemia'
            fullPath: '/saude/glicemia'
            preLoaderRoute: typeof SaudeGlicemiaRouteImport
            parentRoute: typeof SaudeRoute
        }
        '/saude/feminina': {
            id: '/saude/feminina'
            path: '/feminina'
            fullPath: '/saude/feminina'
            preLoaderRoute: typeof SaudeFemininaRouteImport
            parentRoute: typeof SaudeRoute
        }
        '/saude/atividade': {
            id: '/saude/atividade'
            path: '/atividade'
            fullPath: '/saude/atividade'
            preLoaderRoute: typeof SaudeAtividadeRouteImport
            parentRoute: typeof SaudeRoute
        }
        '/saude/alimentacao': {
            id: '/saude/alimentacao'
            path: '/alimentacao'
            fullPath: '/saude/alimentacao'
            preLoaderRoute: typeof SaudeAlimentacaoRouteImport
            parentRoute: typeof SaudeRoute
        }
        '/saude/agua': {
            id: '/saude/agua'
            path: '/agua'
            fullPath: '/saude/agua'
            preLoaderRoute: typeof SaudeAguaRouteImport
            parentRoute: typeof SaudeRoute
        }
    }
}

interface SaudeRouteChildren {
    SaudeAguaRoute: typeof SaudeAguaRoute
    SaudeAlimentacaoRoute: typeof SaudeAlimentacaoRoute
    SaudeAtividadeRoute: typeof SaudeAtividadeRoute
    SaudeFemininaRoute: typeof SaudeFemininaRoute
    SaudeGlicemiaRoute: typeof SaudeGlicemiaRoute
    SaudeHumorRoute: typeof SaudeHumorRoute
    SaudeMedicamentosRoute: typeof SaudeMedicamentosRoute
    SaudePressaoRoute: typeof SaudePressaoRoute
    SaudeIndexRoute: typeof SaudeIndexRoute
}

const SaudeRouteChildren: SaudeRouteChildren = {
    SaudeAguaRoute: SaudeAguaRoute,
    SaudeAlimentacaoRoute: SaudeAlimentacaoRoute,
    SaudeAtividadeRoute: SaudeAtividadeRoute,
    SaudeFemininaRoute: SaudeFemininaRoute,
    SaudeGlicemiaRoute: SaudeGlicemiaRoute,
    SaudeHumorRoute: SaudeHumorRoute,
    SaudeMedicamentosRoute: SaudeMedicamentosRoute,
    SaudePressaoRoute: SaudePressaoRoute,
    SaudeIndexRoute: SaudeIndexRoute,
}

const SaudeRouteWithChildren = SaudeRoute._addFileChildren(SaudeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
    IndexRoute: IndexRoute,
    AvatarRoute: AvatarRoute,
    JogosRoute: JogosRoute,
    MaisRoute: MaisRoute,
    PersonalizarAvatarRoute: PersonalizarAvatarRoute,
    RecompensasRoute: RecompensasRoute,
    SaudeRoute: SaudeRouteWithChildren,
}
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes<FileRouteTypes>()
